import Head from 'next/head'
import Image from 'next/image';
// import {
  // ScrollingProvider,
  // useScrollSection,
  // Section,
// } from 'react-scroll-section';
// import Script from 'next/Script'
// import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import Banner from '../components/Banner';
import AboutUs from '../components/AboutUs';
import OurServices from '../components/OurServices';
import Portofolio from '../components/Portofolio';
import OurClient from '../components/OurClient';
import ContanctUs from '../components/ContactUs';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="wrapper">
      <Head>
        <title>CC Media - Mau bikin Video Cinematic Ga Perlu MAHAL</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
          <Banner />
        {/* <ScrollingProvider> */}
          {/* <Section id="about"> */}
            <AboutUs />
          {/* </Section> */}
          {/* <Section id="about"> */}
            <OurServices /> 
          {/* </Section> */}
        {/* </ScrollingProvider> */}
          <Portofolio />
          <OurClient />
          <ContanctUs />
          <Footer />
      </main>
    </div>
  )
}
