import Head from 'next/head'
import Image from 'next/image'
// import Script from 'next/Script'
// import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import Banner from '../components/Banner';
import AboutUs from '../components/AboutUs';
import OurServices from '../components/OurServices';
import Portofolio from '../components/Portofolio';

export default function Home() {
  return (
    <div className="wrapper">
      <Head>
        <title>CC Media - Mau bikin Video Cinematic Ga Perlu MAHAL</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
        <AboutUs />
        <OurServices /> 
        <Portofolio />
      </main>
    </div>
  )
}
