import Head from 'next/head'
import Image from 'next/image';
import { Element } from 'react-scroll';

// import Script from 'next/Script'
// import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import Banner from '../components/Banner';
import AboutUs from '../components/AboutUs';
import OurServices from '../components/OurServices';
import Portofolio from '../components/Portofolio';
import OurClient from '../components/OurClient';
import ContanctUs from '../components/ContactUs';
import Footer from '../components/Footer';
import Headlines from '../components/Headlines';

export default function Home() {
  return (
    <div className="wrapper">
      <Head>
        <title>CC Media - Mau bikin Video Cinematic Ga Perlu MAHAL</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {/* <Banner /> */}
        <Headlines />
        <Element name="about">
          <AboutUs />
        </Element>
        <Element name="services">
        <OurServices /> 
        </Element>
        <Element name="portofolio">
        <Portofolio />
        </Element>
        <OurClient />
        <Element name="contact">
        <ContanctUs />
        </Element>
      </main>
      <Footer />
    </div>
  )
}
